name: parkeasy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.12.1
  country_picker: ^2.0.21
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.0.1
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/Vehicle/